### ISSUE TITLE
Challenges without -t

### ISSUE THREAD

**Issue by datamattsson** [JensErat/docker-samba-publicshare#1]
I'm having challenges running this image without the -t (tty) option. I'm on Docker 1.12.

**Comment by JensErat** [comment]
Sorry for the late answer. This seems to be because of some change in Docker or Samba. `smbd` terminates immediately after startup if no pseudo-tty is attached. I could not figure out a way to start `smbd` not including hacks that does not require `-t`, and consider providing the argument the better solution that applying hacks inside the image (which might again have other unexpected implications).

I added a note in the description.
